import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header/index";
import Footer from "@/components/footer";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          `${inter.className} flex flex-col justify-between	items-center min-h-screen bg-light dark:bg-dark`
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
